# Generated by Django 3.0.8 on 2020-10-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_spam_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='phone',
        ),
    ]
