# Generated by Django 3.0.8 on 2020-10-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201002_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spam',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Spam',
        ),
    ]
